name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/JabberPoint/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project (navigate to JabberPoint if needed)
    - name: Build with Maven
      run: |
        cd Jabberpoint-IT
        mvn clean install

    # Step 5: Run tests
    - name: Run Tests
      run: |
        cd Jabberpoint-IT
        mvn test

    # Step 6: Run Checkstyle
    - name: Run Checkstyle
      run: |
        cd Jabberpoint-IT
        mvn checkstyle:check

    # Step 7
    - name: Run Tests
      run: |
        cd Jabberpoint-IT
        mvn test

    # Step 8
    - name: Package app (.jar)
      run: |
        cd Jabberpoint-IT
        mvn package

    # Step 9
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: jabberpoint-jar
        path: Jabberpoint-IT/target/*.jar